- name: Reboot Servers
  hosts: all
  tasks:
    - name: reboot
      shell: /sbin/shutdown -r now
      
    - name: wait for return
      local_action: wait_for
      args:
        host: ''
        port: 22
        delay: 30
        timeout: 300
        state: started
