- name: Secure system
  hosts: all
  become: yes
  tasks:
    - name: Disable root ssh
      lineinfile: dest=/etc/ssh/sshd_config
        regexp="^[#P]*ermitRootLogin"
        line="PermitRootLogin no"
        state=present
      notify: Restart ssh

